# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animalito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('especie', models.CharField(choices=[('canino', 'Canino'), ('felino', 'Felino')], max_length=10)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('nro_pre_inscripcion', models.IntegerField()),
                ('turno', models.IntegerField()),
                ('abono', models.IntegerField()),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Campaing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('castracion', 'Castración'), ('vacunacion', 'Vacunación')], max_length=10)),
                ('monto_valor_operacion', models.IntegerField()),
                ('monto_inter_grupo_gastado', models.IntegerField(default=0)),
                ('monto_inter_grupo_total', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('preinscripcion', models.BooleanField(default=True)),
                ('habilitada', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaingColaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padrino', models.BooleanField()),
                ('ayudante', models.BooleanField()),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_campaing.Campaing')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=20)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='app_campaing.Barrio')),
            ],
        ),
        migrations.AddField(
            model_name='campaingcolaborador',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_campaing.Colaborador'),
        ),
        migrations.AddField(
            model_name='campaing',
            name='colaborador',
            field=models.ManyToManyField(through='app_campaing.CampaingColaborador', to='app_campaing.Colaborador'),
        ),
        migrations.AddField(
            model_name='campaing',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaings', to='app_campaing.Lugar'),
        ),
        migrations.AddField(
            model_name='animalito',
            name='campaing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animalitos', to='app_campaing.Campaing'),
        ),
        migrations.AddField(
            model_name='animalito',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animalitos', to='app_campaing.Propietario'),
        ),
        migrations.AlterUniqueTogether(
            name='campaingcolaborador',
            unique_together=set([('campaing', 'colaborador')]),
        ),
    ]
