# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_campaing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalito',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='animalito',
            name='nro_pre_inscripcion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animalito',
            name='user_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
