# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_campaing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalito',
            name='especie',
            field=models.CharField(choices=[('canino', 'CANINO'), ('felino', 'FELINO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animalito',
            name='sexo',
            field=models.CharField(choices=[('macho', 'MACHO'), ('hembra', 'HEMBRA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animalito',
            name='user_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='detalle',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
