# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_campaing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaing',
            name='monto_inter_grupo_gastado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='tipo',
            field=models.CharField(choices=[('castracion', 'Castración'), ('vacunacion', 'Vacunación')], max_length=10),
        ),
    ]
