# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_campaing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalito',
            name='abono',
            field=models.IntegerField(null=True),
        ),
    ]
