# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_campaing', '0002_auto_20171215_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalito',
            name='turno',
            field=models.IntegerField(null=True),
        ),
    ]
