# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_campaing', '0003_auto_20171215_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalito',
            old_name='nombre',
            new_name='nombre_macota',
        ),
    ]
