# Generated by Django 3.1.6 on 2021-02-19 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_campaing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalito',
            name='campaing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animalitos', to='app_campaing.campaing'),
        ),
        migrations.AlterField(
            model_name='animalito',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animalitos', to='app_campaing.propietario'),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaings', to='app_campaing.lugar'),
        ),
        migrations.AlterField(
            model_name='campaingcolaborador',
            name='campaing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_campaing.campaing'),
        ),
        migrations.AlterField(
            model_name='campaingcolaborador',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_campaing.colaborador'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propietario', to='app_campaing.barrio'),
        ),
    ]
